language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"
install:
  - pip install -r requirements-test.txt
  # TensorFlow is optional
  - pip install tensorflow
  - pip install torch
  - pip install -e .
script:
  - python test_deform_grid.py -v
jobs:
  include:
    - name: tensorflow 1.15
      language: python
      python: 3.6
      install:
        - pip install -r requirements-test.txt
        - pip install tensorflow==1.15
        - pip install -e .
