name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    env:
      CIBW_BUILD: cp*

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: choco install vcpython27 -f -y

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      # https://github.com/scipy/oldest-supported-numpy/blob/master/setup.cfg

      - name: Build wheels for CPython 3.5
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp35-*"
          CIBW_BEFORE_BUILD: pip install setuptools numpy==1.13.3

      - name: Build wheels for CPython 3.6
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp36-*"
          CIBW_BEFORE_BUILD: pip install setuptools numpy==1.13.3

      - name: Build wheels for CPython 3.7
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp37-*"
          CIBW_BEFORE_BUILD: pip install setuptools numpy==1.14.5

      - name: Build wheels for CPython 3.8
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-*"
          CIBW_BEFORE_BUILD: pip install setuptools numpy==1.17.3

      - name: Build wheels for CPython 3.9
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_BEFORE_BUILD: pip install setuptools numpy==1.19.3

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
